#!/bin/bash

SEED_IPS=$1
HOST_IP=$2

sed -i -e "s/num_tokens/\#num_tokens/" /opt/cassandra/conf/cassandra.yaml
sed -i -e "s/- seeds: \"127.0.0.1\"/- seeds: \"$SEED_IPS\"/g" /opt/cassandra/conf/cassandra.yaml
sed -i -e "s/listen_address: localhost/listen_address: $HOST_IP/g" /opt/cassandra/conf/cassandra.yaml
sed -i -e "s/rpc_address: localhost/rpc_address: 0.0.0.0/g" /opt/cassandra/conf/cassandra.yaml
sed -i -e "s/endpoint_snitch: SimpleSnitch/endpoint_snitch: GossipingPropertyFileSnitch/g" /opt/cassandra/conf/cassandra.yaml

/opt/cassandra/bin/cassandra -f
